const servers = [
    "http://alpha.webdoseumelhor.top/",
    "http://mwplay.top",
    "http://ratinhov7.click:80",
    "http://ultrabt2.day",
    "http://gigaplay.fun",
    "http://ad.ratinhov4.fun",
    "http://appcnx.site",
    "http://gerenciadorr.click",
    "http://ratinhov10.fun",
    "http://ratinhov5.shop",
    "http://gerenciador6.xyz",
    "http://cdn.ax66.shop",
    "http://ratinhov4.fun",
    "http://ratinhov1.click",
    "http://fhm.ratinhov4.fun",
    "http://c.techzzi.top",
    "http://cf2301.site"
];